name: YouTube View Monitor

on:
  schedule:
    # 매시간 17분 실행
    - cron: "17 * * * *"

  # 수동 실행 버튼
  workflow_dispatch:


jobs:
  monitor:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.12"


      - name: Install packages
        run: |
          pip install -r requirements.txt


      - name: Run monitor
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: |
          python main.py


      - name: Save views
        uses: stefanzweifel/git-auto-commit-action@v5

        with:
          commit_message: Update view count data

        
      - name: Send Telegram failure alert
        if: failure()

        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="⚠️ YouTube Notify GitHub Actions 실패 발생"